Update README.md
teamtuna/android-interview pull request #1
Opened 2019-10-14 06:33 UTC by karrel84

RX의 CompositDisposable관련 내용 추가.

2019-10-15 02:30 UTC, pennya approved these changes

2019-10-15 07:55 UTC, babosamo commented on README.md
> +- RX에서 Observable사용후에 메모리 누수방지를 위해서 어떻게 해야할까요?
맞춤 법이 틀린거 같아요.
```
Observable사용후에 --> Observable 사용 후에
해야할까요 --> 해야 할까요?
```

2019-10-16 13:35 UTC, babosamo requested changes
@karrel84  맞춤법 수정해주세요

2019-10-16 15:09 UTC, eastar-dev approved these changes

2019-10-16 15:09 UTC, eastar-dev approved these changes

2019-10-17 07:48 UTC, babosamo approved these changes

2019-10-17 07:48 UTC, merged